# Generated by Django 4.0.5 on 2022-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('title', models.CharField(default='null', max_length=255)),
                ('isbn13', models.IntegerField(default='null')),
                ('isbn', models.IntegerField(default='null')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profile')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('customer_rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
