# Generated by Django 4.0.5 on 2022-06-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_jsonfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsonFiles',
        ),
    ]
