# Generated by Django 4.0.5 on 2022-06-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_uploadjsonform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadJsonForm',
        ),
    ]
