# Generated by Django 4.0.5 on 2022-06-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_delete_uploadjsonform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculation',
            new_name='SaleItem',
        ),
    ]
