# Generated by Django 4.0.5 on 2022-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_rename_calculation_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='customer_rating',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='isbn',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='isbn13',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
