# Generated by Django 4.0.5 on 2022-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_saleitem_customer_rating_alter_saleitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='image',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
