# Generated by Django 4.0.5 on 2022-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_saleitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='customer_rating',
            field=models.IntegerField(default='null'),
        ),
    ]
