# Generated by Django 4.0.5 on 2022-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_saleitem_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='customer_rating',
            field=models.IntegerField(blank=True, default='null', null=True),
        ),
    ]
