# Generated by Django 4.0.5 on 2022-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_saleitem_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
