# Generated by Django 4.0.5 on 2022-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_saleitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
